/**
 * Wave G — Healing Primitives
 *
 * Seven deterministic, stateless, reversible building blocks for autonomous healing.
 * Compose into healing strategies when drift is detected.
 */

export interface HealingContext {
  plan: PlanNode[];
  criteria: AcceptanceCriteria;
  codeChanges: CodeChange[];
  tests: TestBundle;
  driftSignal: DriftSignal;
  taskId?: string;
}

export interface PlanNode {
  id: string;
  description: string;
  expectedScope?: string[];
  step?: number;
  estimatedEffort?: number;
}

export interface AcceptanceCriteria {
  maxCorruptionPercent?: number;
  minSurvivalPercent?: number;
  requireBackupOnCorruption?: boolean;
  timeoutMs?: number;
  moduleBoundaries?: Record<string, string[]>;
  [key: string]: any;
}

export interface CodeChange {
  file: string;
  additions: number;
  deletions: number;
  hunks: string[];
}

export interface TestBundle {
  failing: string[];
  passing: string[];
  coverage?: number;
}

export interface DriftSignal {
  type: 'KITCHEN_SINK' | 'WRONG_ABSTRACTION' | 'OPTIMISTIC_PATH' | 'RUNAWAY_REFACTOR';
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  details: Record<string, any>;
  timestamp: number;
}

export interface HealingPrimitiveResult {
  primitiveId: string;
  applied: boolean;
  modifiedPlan?: PlanNode[];
  modifiedCriteria?: AcceptanceCriteria;
  modifiedTests?: TestBundle;
  reason: string;
  reversible: boolean;
}

/**
 * Healing Primitives
 */
export class HealingPrimitives {
  /**
   * heal.shrink_scope — reduce plan to single file/function
   *
   * When: KITCHEN_SINK or RUNAWAY_REFACTOR detected
   * Effect: reduce expectedScope to primary file only
   */
  static shrinkScope(ctx: HealingContext): HealingPrimitiveResult {
    const driftFile = ctx.codeChanges[0]?.file || '';

    if (!driftFile) {
      return {
        primitiveId: 'heal.shrink_scope',
        applied: false,
        reason: 'No code changes to scope to',
        reversible: true,
      };
    }

    // Extract module path (e.g., 'src/core/main.ts' → 'src/core')
    const parts = driftFile.split('/');
    const module = parts.slice(0, -1).join('/');

    const modifiedPlan: PlanNode[] = ctx.plan.map((p) => ({
      ...p,
      expectedScope: [module],
    }));

    return {
      primitiveId: 'heal.shrink_scope',
      applied: true,
      modifiedPlan,
      reason: `Reduced scope to primary module: ${module}`,
      reversible: true,
    };
  }

  /**
   * heal.tighten_criteria — rewrite acceptance criteria with explicit module boundaries
   *
   * When: KITCHEN_SINK detected (unrelated files modified)
   * Effect: add moduleBoundaries constraint, reduce thresholds
   */
  static tightenCriteria(ctx: HealingContext): HealingPrimitiveResult {
    const unrelatedFiles = this.getUnrelatedFiles(ctx);

    if (unrelatedFiles.length === 0) {
      return {
        primitiveId: 'heal.tighten_criteria',
        applied: false,
        reason: 'No unrelated files detected',
        reversible: true,
      };
    }

    // Tighten numeric thresholds by 20%
    const modifiedCriteria: AcceptanceCriteria = {
      ...ctx.criteria,
      maxCorruptionPercent: Math.max(0, (ctx.criteria.maxCorruptionPercent || 50) * 0.8),
      minSurvivalPercent: Math.min(100, (ctx.criteria.minSurvivalPercent || 50) * 1.2),
      moduleBoundaries: this.buildModuleBoundaries(ctx.codeChanges),
      _tightenedBy: 'heal.tighten_criteria',
    };

    return {
      primitiveId: 'heal.tighten_criteria',
      applied: true,
      modifiedCriteria,
      reason: `Tightened thresholds. Blocked modules: ${Object.keys(modifiedCriteria.moduleBoundaries || {}).join(', ')}`,
      reversible: true,
    };
  }

  /**
   * heal.inject_negative_tests — auto-add malformed input + failure tests
   *
   * When: OPTIMISTIC_PATH detected (tests exist but no error cases)
   * Effect: add test stubs for error handling
   */
  static injectNegativeTests(ctx: HealingContext): HealingPrimitiveResult {
    const negativeTests = ctx.tests.failing.filter(
      (t) =>
        t.includes('error') ||
        t.includes('invalid') ||
        t.includes('malformed') ||
        t.includes('null') ||
        t.includes('timeout')
    );

    if (negativeTests.length > 0) {
      return {
        primitiveId: 'heal.inject_negative_tests',
        applied: false,
        reason: 'Negative tests already present',
        reversible: true,
      };
    }

    // Generate negative test stubs
    const autoGenerated = [
      'test: handles invalid input gracefully',
      'test: rejects malformed data',
      'test: timeout recovery',
      'test: null-reference protection',
      'test: error boundary containment',
    ];

    const modifiedTests: TestBundle = {
      failing: [...ctx.tests.failing, ...autoGenerated],
      passing: ctx.tests.passing,
      coverage: Math.min((ctx.tests.coverage || 0) + 20, 100),
    };

    return {
      primitiveId: 'heal.inject_negative_tests',
      applied: true,
      modifiedTests,
      reason: `Injected ${autoGenerated.length} negative test stubs`,
      reversible: true,
    };
  }

  /**
   * heal.enforce_surgical_diff — cap file modifications to ≤1
   *
   * When: RUNAWAY_REFACTOR detected (too many files changed)
   * Effect: reduce scope to single file
   */
  static enforceSurgicalDiff(ctx: HealingContext): HealingPrimitiveResult {
    if (ctx.codeChanges.length <= 1) {
      return {
        primitiveId: 'heal.enforce_surgical_diff',
        applied: false,
        reason: 'Already surgical (≤1 file)',
        reversible: true,
      };
    }

    // Keep primary change, discard rest
    const primary = ctx.codeChanges[0];

    const modifiedPlan: PlanNode[] = ctx.plan.map((p) => ({
      ...p,
      expectedScope: [primary.file],
      description: `${p.description} (surgical scope: ${primary.file})`,
    }));

    return {
      primitiveId: 'heal.enforce_surgical_diff',
      applied: true,
      modifiedPlan,
      reason: `Reduced ${ctx.codeChanges.length} files → 1 file (${primary.file})`,
      reversible: true,
    };
  }

  /**
   * heal.freeze_architecture — block refactors, renames, module moves
   *
   * When: RUNAWAY_REFACTOR detected with high cascading depth
   * Effect: add explicit constraint blocking structural changes
   */
  static freezeArchitecture(ctx: HealingContext): HealingPrimitiveResult {
    const hasRefactorLogs = ctx.driftSignal.details.refactorLogs?.length > 0;

    if (!hasRefactorLogs && ctx.driftSignal.type !== 'RUNAWAY_REFACTOR') {
      return {
        primitiveId: 'heal.freeze_architecture',
        applied: false,
        reason: 'No refactor activity detected',
        reversible: true,
      };
    }

    const modifiedCriteria: AcceptanceCriteria = {
      ...ctx.criteria,
      _architectureFrozen: true,
      _frozenRules: [
        'no module renames',
        'no directory moves',
        'no interface changes',
        'no dependency reordering',
      ],
      _reason: 'heal.freeze_architecture',
    };

    return {
      primitiveId: 'heal.freeze_architecture',
      applied: true,
      modifiedCriteria,
      reason: 'Architecture frozen: renames/moves/restructuring blocked',
      reversible: true,
    };
  }

  /**
   * heal.require_abstraction_step — force extraction of shared logic
   *
   * When: WRONG_ABSTRACTION detected (code duplication)
   * Effect: require explicit abstraction step in plan
   */
  static requireAbstractionStep(ctx: HealingContext): HealingPrimitiveResult {
    if (ctx.driftSignal.type !== 'WRONG_ABSTRACTION') {
      return {
        primitiveId: 'heal.require_abstraction_step',
        applied: false,
        reason: 'No duplication detected',
        reversible: true,
      };
    }

    const abstractionStep: PlanNode = {
      id: 'abstraction-step',
      description: 'Extract duplicated logic into shared module',
      expectedScope: this.getDuplicateModules(ctx),
      step: 0,
      estimatedEffort: 4, // 4h effort for extraction
    };

    const modifiedPlan: PlanNode[] = [abstractionStep, ...ctx.plan];

    return {
      primitiveId: 'heal.require_abstraction_step',
      applied: true,
      modifiedPlan,
      reason: `Added abstraction step: extract ${abstractionStep.expectedScope?.join(', ') || 'duplicated logic'}`,
      reversible: true,
    };
  }

  /**
   * heal.require_dependency_justification — block un-justified deps
   *
   * When: new dependencies added without rationale
   * Effect: require explicit justification field in criteria
   */
  static requireDependencyJustification(ctx: HealingContext): HealingPrimitiveResult {
    // Extract potential new deps from code changes
    const depPattern = /import.*from\s+['"]([@\w-]+)['"]/g;
    const deps = new Set<string>();

    for (const change of ctx.codeChanges) {
      for (const hunk of change.hunks) {
        let match;
        // eslint-disable-next-line no-cond-assign
        while ((match = depPattern.exec(hunk)) !== null) {
          deps.add(match[1]);
        }
      }
    }

    if (deps.size === 0) {
      return {
        primitiveId: 'heal.require_dependency_justification',
        applied: false,
        reason: 'No new dependencies detected',
        reversible: true,
      };
    }

    const modifiedCriteria: AcceptanceCriteria = {
      ...ctx.criteria,
      _dependencyJustification: {
        ...Object.fromEntries(Array.from(deps).map((d) => [d, 'PENDING'])),
        _rule: 'All new dependencies require explicit justification before merge',
      },
    };

    return {
      primitiveId: 'heal.require_dependency_justification',
      applied: true,
      modifiedCriteria,
      reason: `Flagged ${deps.size} new deps for justification: ${Array.from(deps).join(', ')}`,
      reversible: true,
    };
  }

  /**
   * Compose healing strategy from primitives
   */
  static compose(ctx: HealingContext, primitives: string[]): HealingPrimitiveResult[] {
    const results: HealingPrimitiveResult[] = [];
    let currentCtx = { ...ctx };

    for (const primitive of primitives) {
      let result: HealingPrimitiveResult;

      switch (primitive) {
        case 'heal.shrink_scope':
          result = this.shrinkScope(currentCtx);
          break;
        case 'heal.tighten_criteria':
          result = this.tightenCriteria(currentCtx);
          break;
        case 'heal.inject_negative_tests':
          result = this.injectNegativeTests(currentCtx);
          break;
        case 'heal.enforce_surgical_diff':
          result = this.enforceSurgicalDiff(currentCtx);
          break;
        case 'heal.freeze_architecture':
          result = this.freezeArchitecture(currentCtx);
          break;
        case 'heal.require_abstraction_step':
          result = this.requireAbstractionStep(currentCtx);
          break;
        case 'heal.require_dependency_justification':
          result = this.requireDependencyJustification(currentCtx);
          break;
        default:
          result = {
            primitiveId: primitive,
            applied: false,
            reason: 'Unknown primitive',
            reversible: false,
          };
      }

      // Update context for next primitive
      if (result.applied) {
        if (result.modifiedPlan) currentCtx.plan = result.modifiedPlan;
        if (result.modifiedCriteria) currentCtx.criteria = result.modifiedCriteria;
        if (result.modifiedTests) currentCtx.tests = result.modifiedTests;
      }

      results.push(result);
    }

    return results;
  }

  // Helpers

  private static getUnrelatedFiles(ctx: HealingContext): CodeChange[] {
    const expectedScope = ctx.plan.flatMap((p) => p.expectedScope || []);
    if (expectedScope.length === 0) return [];

    return ctx.codeChanges.filter(
      (diff) => !expectedScope.some((scope) => diff.file.includes(scope))
    );
  }

  private static buildModuleBoundaries(
    changes: CodeChange[]
  ): Record<string, string[]> {
    const boundaries: Record<string, string[]> = {};

    for (const change of changes) {
      const parts = change.file.split('/');
      const module = parts.slice(0, -1).join('/');
      if (!boundaries[module]) {
        boundaries[module] = [];
      }
      boundaries[module].push(change.file);
    }

    return boundaries;
  }

  private static getDuplicateModules(ctx: HealingContext): string[] {
    const duplicates = ctx.driftSignal.details.blocks || [];
    const modules = new Set<string>();

    for (const dup of duplicates) {
      const lines = (dup as string).split('\n');
      for (const line of lines) {
        const match = line.match(/from\s+['"]([@.\w/-]+)['"]/);
        if (match) {
          modules.add(match[1]);
        }
      }
    }

    return Array.from(modules);
  }
}
